global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      environment: $PLACEHOLDER

scrape_configs:

- job_name: 'rancher-discovery'
  file_sd_configs:
  - files:
    - /etc/prom-conf/prom-rancher-sd/rancher.json
